export const TEAMS: any = [

    {
        teamId: 1,
        name: 'Boston Celtics',
        gamesPlayed: 50,
        wins: 38,
        losses: 12,
        minutesPlayed: 48.5,
        points: 120.3,
        fieldGoalsMade: 43.2,
        fieldGoalsAttempted: 90.2,
        threePointFieldGoalsMade: 16.2,
        threePointFieldGoalsAttempted: 42.9,
        freeThrowsMade: 17.7,
        freeThrowsAttempted: 22.0,
        offensiveRebounds: 11.0,
        defensiveRebounds: 36.5,
        rebounds: 47.5,
        assists: 25.9,
        turnovers: 12.6,
        steals: 6.4,
        blocks: 6.6,
        personalFouls: 17.1,
        plusMinus: 9.6,

        record: '38 - 12',
        placement: '1st in Eastern',
        pointsPerGame: 120.3,
        reboundsPerGame: 47.5,
        assistsPerGame: 25.9,

        roster: ['Jayson Tatum', 'Kristaps Porzingis', 'Jaylen Brown', 'Derrick White', 'Jrue Holiday',
                 'Neemias Queta', 'Jordan Walsh', 'Payton Pritchard', 'Al Horford', 'Sam Hauser', 'Luke Kornet',
                 'Oshae Brissett', 'Dalano Banton', 'Sviatoslav Mykhailiuk', 'Lamar Stevens', 'Jerdarrian Devontae Davison',
                 'Drew Peterson'],
        conference: 'Eastern'
    },

    {
        teamId: 2,
        name: 'Brooklyn Nets',
        gamesPlayed: 49,
        wins: 20,
        losses: 29,
        minutesPlayed: 48.3,
        points: 114.3,
        fieldGoalsMade: 42.0,
        fieldGoalsAttempted: 91.2,
        threePointFieldGoalsMade: 13.9,
        threePointFieldGoalsAttempted: 38.2,
        freeThrowsMade: 16.3,
        freeThrowsAttempted: 21.5,
        offensiveRebounds: 12.0,
        defensiveRebounds: 33.2,
        rebounds: 45.2,
        assists: 26.7,
        turnovers: 12.7,
        steals: 6.9,
        blocks: 5.5,
        personalFouls: 19.3,
        plusMinus: -1.0,

        record: '20 - 29',
        placement: '11th in Eastern',
        pointsPerGame: 114.3,
        reboundsPerGame: 45.2,
        assistsPerGame: 26.7,

        roster: ['Keita Bates-Diop', 'Mikal Bridges', 'Nicolas Claxton', 'Noah Clowney',
                 'Dorian Finney-Smith', 'Cameron Johnson', 'Dennis Schroder', 'Day\'Ron Sharpe',
                 'Ben Simmons', 'Dennis Smith Jr.', 'Cam Thomas', 'Lonnie Walker IV', 'Trendon Watford',
                 'Dariq Whitehead'],
        conference: 'Eastern'
    },

    {
        teamId: 3,
        name: 'Charlotte Hornets',
        gamesPlayed: 49,
        wins: 10,
        losses: 39,
        minutesPlayed: 48.2,
        points: 108.5,
        fieldGoalsMade: 40.8,
        fieldGoalsAttempted: 89.1,
        threePointFieldGoalsMade: 11.9,
        threePointFieldGoalsAttempted: 33.0,
        freeThrowsMade: 15.0,
        freeThrowsAttempted: 19.1,
        offensiveRebounds: 10.3,
        defensiveRebounds: 30.5,
        rebounds: 40.8,
        assists: 24.8,
        turnovers: 13.6,
        steals: 6.6,
        blocks: 4.9,
        personalFouls: 19.3,
        plusMinus: -11.8,

        record: '10 - 39',
        placement: '13th in Eastern',
        pointsPerGame: 108.5,
        reboundsPerGame: 40.8,
        assistsPerGame: 24.8,

        roster: ['LaMelo Ball', 'Davis Bertans', 'Miles Bridges', 'Seth Curry', 'Kyle Lowry', 'Tre Mann',
                 'Cody Martin', 'Bryce McGowens', 'Vasilije Micic', 'Brandon Miller', 'Nick Richards', 'Nick Smith Jr.',
                 'JT Thor', 'Grant Williams', 'Mark Williams'],
        conference: 'Eastern'
    },

    {
        teamId: 4,
        name: 'Chicago Bulls',
        gamesPlayed: 50,
        wins: 23,
        losses: 27,
        minutesPlayed: 48.6,
        points: 111.1,
        fieldGoalsMade: 41.4,
        fieldGoalsAttempted: 89.2,
        threePointFieldGoalsMade: 11.7,
        threePointFieldGoalsAttempted: 32.8,
        freeThrowsMade: 16.5,
        freeThrowsAttempted: 20.9,
        offensiveRebounds: 11.0,
        defensiveRebounds: 32.3,
        rebounds: 43.3,
        assists: 24.5,
        turnovers: 12.4,
        steals: 7.8,
        blocks: 5.1,
        personalFouls: 19.1,
        plusMinus: -1.6,

        record: '23 - 27',
        placement: '9th in Eastern',
        pointsPerGame: 111.1,
        reboundsPerGame: 43.3,
        assistsPerGame: 24.5,

        roster: ['Lonzo Ball', 'Jevon Carter', 'Alex Caruso', 'Torrey Craig', 'DeMar DeRozan', 'Ayo Dosunmu',
                 'Andre Drummond', 'Zach LaVine', 'Julian Phillips', 'Terry Taylor', 'Dalen Terry', 'Nikola Vucevic', 'Coby White', 'Patrick Williams'],
        conference: 'Eastern'
    },
    
    {
        teamId: 5,
        name: 'Cleveland Cavaliers',
        gamesPlayed: 48,
        wins: 32,
        losses: 16,
        minutesPlayed: 48.2,
        points: 114.8,
        fieldGoalsMade: 42.7,
        fieldGoalsAttempted: 88.8,
        threePointFieldGoalsMade: 13.4,
        threePointFieldGoalsAttempted: 37.0,
        freeThrowsMade: 16.0,
        freeThrowsAttempted: 20.8,
        offensiveRebounds: 10.8,
        defensiveRebounds: 34.3,
        rebounds: 45.1,
        assists: 27.0,
        turnovers: 13.6,
        steals: 7.8,
        blocks: 4.6,
        personalFouls: 18.8,
        plusMinus: 5.1,

        record: '32 - 16',
        placement: '2nd in Eastern',
        pointsPerGame: 114.8,
        reboundsPerGame: 45.1,
        assistsPerGame: 27.0,

        roster: ['Jarrett Allen', 'Darius Garland', 'Ty Jerome', 'Damian Jones', 'Caris LeVert', 
                 'Sam Merrill', 'Donovan Mitchell', 'Evan Mobley', 'Georges Niang', 'Isaac Okoro', 'Max Strus', 'Dean Wade'],
        conference: 'Eastern'
    },

    {
        teamId: 6,
        name: 'Dallas Mavericks',
        gamesPlayed: 50,
        wins: 27,
        losses: 23,
        minutesPlayed: 48.0,
        points: 118.2,
        fieldGoalsMade: 42.6,
        fieldGoalsAttempted: 89.7,
        threePointFieldGoalsMade: 15.1,
        threePointFieldGoalsAttempted: 40.6,
        freeThrowsMade: 18.0,
        freeThrowsAttempted: 23.7,
        offensiveRebounds: 10.0,
        defensiveRebounds: 31.4,
        rebounds: 41.4,
        assists: 25.3,
        turnovers: 12.4,
        steals: 6.6,
        blocks: 4.3,
        personalFouls: 19.2,
        plusMinus: -0.3,

        record: '27 - 23',
        placement: '8th in Western',
        pointsPerGame: 118.2,
        reboundsPerGame: 41.5,
        assistsPerGame: 25.3,

        roster: ['Luka Doncic', 'Dante Exum', 'Daniel Gafford', 'Josh Green', 'Tim Hardaway Jr.', 'Jaden Hardy', 'Kyrie Irving', 'Derrick Jones Jr.',
                 'Maxi Kleber', 'Dereck Lively II', 'Markieff Morris', 'Dwight Powell', 'Olivier-Maxence Prosper', 'P.J. Washington'],
        conference: 'Western'
    },

    {
        teamId: 7,
        name: 'Denver Nuggets',
        gamesPlayed: 51,
        wins: 35,
        losses: 16,
        minutesPlayed: 48.0,
        points: 114.8,
        fieldGoalsMade: 43.8,
        fieldGoalsAttempted: 88.6,
        threePointFieldGoalsMade: 11.5,
        threePointFieldGoalsAttempted: 31.1,
        freeThrowsMade: 15.7,
        freeThrowsAttempted: 20.8,
        offensiveRebounds: 11.0,
        defensiveRebounds: 33.0,
        rebounds: 44.0,
        assists: 28.7,
        turnovers: 12.4,
        steals: 6.8,
        blocks: 5.4,
        personalFouls: 18.7,
        plusMinus: 4.2,

        record: '35 - 16',
        placement: '4th in Western',
        pointsPerGame: 114.8,
        reboundsPerGame: 44.1,
        assistsPerGame: 28.7,

        roster: ['Christian Braun', 'Kentavious Caldwell-Pope', 'Vlatko Cancar', 'Aaron Gordon', 'Justin Holiday',
                 'Reggie Jackson', 'Nikola Jokic', 'DeAndre Jordan', 'Jamal Murray', 'Zeke Nnaji', 'Jalen Pickett',
                 'Michael Porter Jr.', 'Julian Strawther', 'Hunter Tyson', 'Peyton Watson'],
        conference: 'Western'
    },

    {
        teamId: 8,
        name: 'Detroit Pistons',
        gamesPlayed: 49,
        wins: 6,
        losses: 43,
        minutesPlayed: 48.2,
        points: 112.6,
        fieldGoalsMade: 42.1,
        fieldGoalsAttempted: 88.8,
        threePointFieldGoalsMade: 11.1,
        threePointFieldGoalsAttempted: 31.1,
        freeThrowsMade: 17.4,
        freeThrowsAttempted: 22.4,
        offensiveRebounds: 11.0,
        defensiveRebounds: 32.1,
        rebounds: 43.1,
        assists: 26.3,
        turnovers: 15.6,
        steals: 5.9,
        blocks: 5.0,
        personalFouls: 21.8,
        plusMinus: -9.7,

        record: '6 - 43',
        placement: '15th in Eastern',
        pointsPerGame: 112.6,
        reboundsPerGame: 43.1,
        assistsPerGame: 26.3,

        roster: ['Troy Brown Jr.', 'Cade Cunningham', 'Jalen Duren', 'Malachi Flynn', 'Simone Fontecchio', 'Evan Fournier', 'Quentin Grimes', 'Jaden Ivey', 
                 'Shake Milton', 'Mike Muscala', 'Marcus Sasser', 'Isaiah Stewart', 'Ausar Thompson', 'James Wiseman'],
        conference: 'Eastern'
    },

    {
        teamId: 9,
        name: 'Golden State Warriors',
        gamesPlayed: 47,
        wins: 22,
        losses: 25,
        minutesPlayed: 48.6,
        points: 118.7,
        fieldGoalsMade: 43.0,
        fieldGoalsAttempted: 91.2,
        threePointFieldGoalsMade: 14.8,
        threePointFieldGoalsAttempted: 39.6,
        freeThrowsMade: 17.9,
        freeThrowsAttempted: 22.6,
        offensiveRebounds: 12.4,
        defensiveRebounds: 34.0,
        rebounds: 46.4,
        assists: 28.4,
        turnovers: 14.5,
        steals: 6.6,
        blocks: 4.0,
        personalFouls: 20.7,
        plusMinus: 0.3,

        record: '22 - 25',
        placement: '12th in Western',
        pointsPerGame: 118.7,
        reboundsPerGame: 46.4,
        assistsPerGame: 28.4,

        roster: ['Stephen Curry', 'Draymond Green', 'Trayce Jackson-Davis', 'Jonathan Kuminga', 'Kevon Looney', 'Moses Moody',
                 'Chris Paul', 'Gary Payton II', 'Brandin Podziemski', 'Gui Santos', 'Dario Saric', 'Klay Thompson', 'Andrew Wiggins'],
        conference: 'Western'
    },

    {
        teamId: 10,
        name: 'Houston Rockets',
        gamesPlayed: 49,
        wins: 23,
        losses: 26,
        minutesPlayed: 48.5,
        points: 113.4,
        fieldGoalsMade: 41.5,
        fieldGoalsAttempted: 89.7,
        threePointFieldGoalsMade: 12.0,
        threePointFieldGoalsAttempted: 34.2,
        freeThrowsMade: 18.4,
        freeThrowsAttempted: 23.6,
        offensiveRebounds: 10.5,
        defensiveRebounds: 34.8,
        rebounds: 45.3,
        assists: 25.1,
        turnovers: 12.7,
        steals: 7.5,
        blocks: 4.4,
        personalFouls: 21.5,
        plusMinus: 1.1,

        record: '23 - 26',
        placement: '11th in Western',
        pointsPerGame: 113.5,
        reboundsPerGame: 45.6,
        assistsPerGame: 25.0,

        roster: ['Steven Adams', 'Dillon Brooks', 'Reggie Bullock', 'Tari Eason', 'Jalen Green', 'Jeff Green', 'Aaron Holiday', 'Jock Landale', 'Boban Marjanovic',
                 'Alperen Sengun', 'Jabari Smith Jr.', 'Jae\'Sean Tate', 'Amen Thompson', 'Fred VanVleet', 'Cam Whitmore'],
        conference: 'Western'
    },

    {
        teamId: 11,
        name: 'Indiana Pacers',
        gamesPlayed: 51,
        wins: 28,
        losses: 23,
        minutesPlayed: 48.0,
        points: 124.2,
        fieldGoalsMade: 46.9,
        fieldGoalsAttempted: 92.8,
        threePointFieldGoalsMade: 13.7,
        threePointFieldGoalsAttempted: 36.1,
        freeThrowsMade: 16.8,
        freeThrowsAttempted: 21.3,
        offensiveRebounds: 10.4,
        defensiveRebounds: 30.9,
        rebounds: 41.4,
        assists: 30.8,
        turnovers: 13.6,
        steals: 7.7,
        blocks: 5.9,
        personalFouls: 22.4,
        plusMinus: 1.8,

        record: '28 - 23',
        placement: '6th in Eastern',
        pointsPerGame: 124.1,
        reboundsPerGame: 40.8,
        assistsPerGame: 30.9,

        roster: ['Tyrese Haliburton', 'Isaiah Jackson', 'Bennedict Mathurin', 'T.J. McConnell', 'Doug McDermott',
                 'Andrew Nembhard', 'Aaron Nesmith', 'Ben Sheppard', 'Pascal Siakam', 'Jalen Smith', 'Obi Toppin',
                 'Myles Turner', 'Jarace Walker'],
        conference: 'Eastern'
    },

    {
        teamId: 12,
        name: 'Los Angeles Clippers',
        gamesPlayed: 49,
        wins: 34,
        losses: 15,
        minutesPlayed: 48.1,
        points: 118.8,
        fieldGoalsMade: 43.5,
        fieldGoalsAttempted: 87.6,
        threePointFieldGoalsMade: 13.3,
        threePointFieldGoalsAttempted: 33.2,
        freeThrowsMade: 18.6,
        freeThrowsAttempted: 22.9,
        offensiveRebounds: 10.4,
        defensiveRebounds: 32.9,
        rebounds: 43.3,
        assists: 26.3,
        turnovers: 12.9,
        steals: 8.1,
        blocks: 5.3,
        personalFouls: 19.5,
        plusMinus: 6.4,

        record: '34 - 15',
        placement: '3rd in Western',
        pointsPerGame: 118.4,
        reboundsPerGame: 43.0,
        assistsPerGame: 26.1,

        roster: ['Brandon Boston Jr.', 'Kobe Brown', 'Amir Coffey', 'Paul George', 'James Harden', 'Bones Hyland', 'Kawhi Leonard',
                 'Terance Mann', 'Mason Plumlee', 'Norman Powell', 'Joshua Primo', 'Daniel Theis', 'P.J. Tucker', 'Russell Westbrook', 'Ivica Zubac'],
        conference: 'Western'
    },

    {
        teamId: 13,
        name: 'Los Angeles Lakers',
        gamesPlayed: 52,
        wins: 27,
        losses: 25,
        minutesPlayed: 48.4,
        points: 116.2,
        fieldGoalsMade: 43.0,
        fieldGoalsAttempted: 87.5,
        threePointFieldGoalsMade: 11.3,
        threePointFieldGoalsAttempted: 30.7,
        freeThrowsMade: 19.0,
        freeThrowsAttempted: 24.6,
        offensiveRebounds: 8.3,
        defensiveRebounds: 34.7,
        rebounds: 43.0,
        assists: 28.3,
        turnovers: 14.1,
        steals: 7.9,
        blocks: 5.5,
        personalFouls: 16.4,
        plusMinus: -0.9,

        record: '27 - 25',
        placement: '9th in Western',
        pointsPerGame: 116.5,
        reboundsPerGame: 42.7,
        assistsPerGame: 28.3,

        roster: ['Max Christie', 'Anthony Davis', 'Spencer Dinwiddie', 'Rui Hachimura', 'Jaxson Hayes', 'Jalen Schifino-Hood',
                 'LeBron James', 'Maxwell Lewis', 'Taurean Prince', 'Austin Reaves', 'Cam Reddish', 'D\'Angelo Russell', 'Jarred Vanderbilt',
                 'Gabe Vincent', 'Christian Wood'],
        conference: 'Western'
    },

    {
        teamId: 14,
        name: 'Memphis Grizzlies',
        gamesPlayed: 50,
        wins: 18,
        losses: 32,
        minutesPlayed:48.2 ,
        points: 106.9,
        fieldGoalsMade: 38.6,
        fieldGoalsAttempted: 88.4,
        threePointFieldGoalsMade: 13.5,
        threePointFieldGoalsAttempted: 39.2,
        freeThrowsMade: 16.2,
        freeThrowsAttempted: 21.0,
        offensiveRebounds: 10.2,
        defensiveRebounds: 32.1,
        rebounds: 42.2,
        assists: 24.9,
        turnovers: 14.7,
        steals: 7.7,
        blocks: 6.2,
        personalFouls: 19.8,
        plusMinus: -6.1,

        record: '18 - 32',
        placement: '13th in Western',
        pointsPerGame: 107.1,
        reboundsPerGame: 41.7,
        assistsPerGame: 25.2,

        roster: ['Santi Aldama', 'Desmond Bane', 'Brandon Clarke', 'GG Jackson', 'Jaren Jackson Jr.', 'Luke Kennard', 'John Konchar',
                 'Jake LaRavia', 'Ja Morant', 'Derrick Rose', 'Marcus Smart', 'Lamar Stevens', 'Yuta Watanabe', 'Vince Williams Jr.', 'Ziaire Williams'],
        conference: 'Western'
    },

    {
        teamId: 15,
        name: 'Miami Heat',
        gamesPlayed: 50,
        wins: 26,
        losses: 24,
        minutesPlayed: 48.1,
        points: 110.1,
        fieldGoalsMade: 39.3,
        fieldGoalsAttempted: 85.5,
        threePointFieldGoalsMade: 12.3,
        threePointFieldGoalsAttempted: 33.0,
        freeThrowsMade: 19.2,
        freeThrowsAttempted: 23.3,
        offensiveRebounds: 9.7,
        defensiveRebounds: 32.3,
        rebounds: 42.0,
        assists: 25.7,
        turnovers: 13.1,
        steals: 7.2,
        blocks: 3.2,
        personalFouls: 18.2,
        plusMinus: -1.1,

        record: '26 - 24',
        placement: '8th in Eastern',
        pointsPerGame: 110.5,
        reboundsPerGame: 42.1,
        assistsPerGame: 25.9,

        roster: ['Bam Adebayo', 'Thomas Bryant', 'Jimmy Butler', 'Tyler Herro', 'Haywood Highsmith',
                 'Jaime Jaquez Jr.', 'Nikola Jovic', 'Kevin Love', 'Terry Rozier', 'Caleb Martin',
                 'Josh Richardson', 'Duncan Robinson', 'Orlando Robinson', 'Dru Smith'],
        conference: 'Eastern'
    },

    {
        teamId: 16,
        name: 'Milwaukee Bucks',
        gamesPlayed: 50,
        wins: 33,
        losses: 17,
        minutesPlayed: 48.3,
        points: 123.7,
        fieldGoalsMade: 44.5,
        fieldGoalsAttempted: 89.5,
        threePointFieldGoalsMade: 14.2,
        threePointFieldGoalsAttempted: 37.6,
        freeThrowsMade: 20.4,
        freeThrowsAttempted: 26.4,
        offensiveRebounds: 9.4,
        defensiveRebounds: 34.6,
        rebounds: 44.0,
        assists: 26.7,
        turnovers: 12.9,
        steals: 6.7,
        blocks: 5.3,
        personalFouls: 20.3,
        plusMinus: 3.7,

        record: '33 - 17',
        placement: '3rd in Eastern',
        pointsPerGame: 122.9,
        reboundsPerGame: 44.0,
        assistsPerGame: 26.8,

        roster: ['Giannis Antetokounmpo', 'Thanasis Antetokounmpo', 'Malik Beasley', 'MarJon Beauchamp', 'Patrick Beverley',
                 'Pat Connaughton', 'Jae Crowder', 'A.J. Green', 'Andre Jackson Jr.', 'Damian Lillard',
                 'Chris Livingston', 'Brook Lopez', 'Khris Middleton', 'Bobby Portis Jr.'],
        conference: 'Eastern'
    },

    {
        teamId: 17,
        name: 'Minnesota Timberwolves',
        gamesPlayed: 50,
        wins: 35,
        losses: 15,
        minutesPlayed: 48.2,
        points: 112.9,
        fieldGoalsMade: 41.1,
        fieldGoalsAttempted: 84.0,
        threePointFieldGoalsMade: 12.3,
        threePointFieldGoalsAttempted: 31.5,
        freeThrowsMade: 18.5,
        freeThrowsAttempted: 23.7,
        offensiveRebounds: 9.0,
        defensiveRebounds: 34.8,
        rebounds: 43.9,
        assists: 26.2,
        turnovers: 15.1,
        steals: 7.5,
        blocks: 5.9,
        personalFouls: 19.4,
        plusMinus: 6.2,

        record: '35 - 15',
        placement: '1st in Western',
        pointsPerGame: 113.4,
        reboundsPerGame: 43.8,
        assistsPerGame: 26.4,

        roster: ['Nickeil Alexander-Walker', 'Kyle Anderson', 'Mike Conley', 'Anthony Edwards', 'Rudy Gobert', 'Jaden McDaniels',
                 'Jordan McLaughlin', 'Leonard Miller', 'Josh Minott', 'Wendell Moore Jr.', 'Monte Morris', 'Naz Reid', 'Karl-Anthony Towns'],
        conference: 'Western'
    },

    {
        teamId: 18,
        name: 'New Orleans Pelicans',
        gamesPlayed: 50,
        wins: 29,
        losses: 21,
        minutesPlayed: 48.1,
        points: 116.9,
        fieldGoalsMade: 43.0,
        fieldGoalsAttempted: 88.2,
        threePointFieldGoalsMade: 12.2,
        threePointFieldGoalsAttempted: 32.2,
        freeThrowsMade: 18.7,
        freeThrowsAttempted: 24.5,
        offensiveRebounds: 11.1,
        defensiveRebounds: 33.5,
        rebounds: 44.6,
        assists: 26.9,
        turnovers: 13.2,
        steals: 8.2,
        blocks: 4.7,
        personalFouls: 19.2,
        plusMinus: 4.3,

        record: '29 - 21',
        placement: '6th in Western',
        pointsPerGame: 116.5,
        reboundsPerGame: 44.2,
        assistsPerGame: 27.0,

        roster: ['Jose Alvarado', 'Dyson Daniels', 'Jordan Hawkins', 'Brandon Ingram', 'Herbert Jones', 'E.J. Liddell', 'Naji Marshall', 'CJ McCollum', 'Trey Murphy III',
                 'Larry Nance Jr.', 'Jonas Valanciunas', 'Zion Williamson', 'Cody Zeller'],
        conference: 'Western'
    },

    {
        teamId: 19,
        name: 'New York Knicks',
        gamesPlayed: 50,
        wins: 32,
        losses: 18,
        minutesPlayed: 48.0,
        points: 115.0,
        fieldGoalsMade: 41.7,
        fieldGoalsAttempted: 89.3,
        threePointFieldGoalsMade: 13.1,
        threePointFieldGoalsAttempted: 35.5,
        freeThrowsMade: 18.5,
        freeThrowsAttempted: 23.6,
        offensiveRebounds: 12.8,
        defensiveRebounds: 33.7,
        rebounds: 46.4,
        assists: 23.9,
        turnovers: 13.2,
        steals: 7.3,
        blocks: 4.0,
        personalFouls: 18.3,
        plusMinus: 5.8,

        record: '32 - 18',
        placement: '4th in Eastern',
        pointsPerGame: 115.0,
        reboundsPerGame: 46.0,
        assistsPerGame: 23.9,

        roster: ['Precious Achiuwa', 'O.G. Anunoby', 'Bojan Bogdanovic', 'Jalen Brunson', 
                 'Alec Burks', 'Donte DiVincenzo', 'Taj Gibson', 'Josh Hart', 'Isaiah Hartenstein',
                 'Miles McBride', 'Julius Randle', 'Mitchell Robinson', 'Jericho Sims'],
        conference: 'Eastern'
    },

    {
        teamId: 20,
        name: 'Oklahoma City Thunder',
        gamesPlayed: 50,
        wins: 35,
        losses: 15,
        minutesPlayed: 48.4,
        points: 120.8,
        fieldGoalsMade: 44.6,
        fieldGoalsAttempted: 89.0,
        threePointFieldGoalsMade: 13.2,
        threePointFieldGoalsAttempted: 33.8,
        freeThrowsMade: 18.4,
        freeThrowsAttempted: 22.1,
        offensiveRebounds: 8.7,
        defensiveRebounds: 32.9,
        rebounds: 41.6,
        assists: 27.3,
        turnovers: 12.6,
        steals: 8.2,
        blocks: 6.6,
        personalFouls: 19.6,
        plusMinus: 8.0,

        record: '35 - 15',
        placement: '2nd in Western',
        pointsPerGame: 120.6,
        reboundsPerGame: 41.3,
        assistsPerGame: 27.2,

        roster: ['Bismack Biyombo', 'Ousmane Dieng', 'Luguentz Dort', 'Josh Giddey', 'Shai Gilgeous-Alexander',
                 'Gordon Hayward', 'Chet Holmgren', 'Isaiah Joe', 'Aleksej Pokusevski', 'Cason Wallace', 'Lindy Waters III', 'Aaron Wiggins', 'Jalen Williams',
                 'Jaylin Williams', 'Kenrich Williams'],
        conference: 'Western'
    },

    {
        teamId: 21,
        name: 'Orlando Magic',
        gamesPlayed: 50,
        wins: 27,
        losses: 23,
        minutesPlayed: 48.3,
        points: 111.6,
        fieldGoalsMade: 40.5,
        fieldGoalsAttempted: 86.3,
        threePointFieldGoalsMade: 10.7,
        threePointFieldGoalsAttempted: 31.1,
        freeThrowsMade: 19.8,
        freeThrowsAttempted: 26.1,
        offensiveRebounds: 11.1,
        defensiveRebounds: 31.9,
        rebounds: 43.0,
        assists: 24.6,
        turnovers: 14.5,
        steals: 8.2,
        blocks: 5.3,
        personalFouls: 21.2,
        plusMinus: 1.0,

        record: '27 - 23',
        placement: '7th in Eastern',
        pointsPerGame: 111.6,
        reboundsPerGame: 42.9,
        assistsPerGame: 24.8,

        roster: ['Cole Anthony', 'Paolo Banchero', 'Goga Bitadze', 'Anthony Black', 'Wendell Carter Jr.', 'Markelle Fultz',
                 'Gary Harris', 'Caleb Houstan', 'Jett Howard', 'Joe Ingles', 'Jonathan Isaac', 'Chuma Okeke', 'Jalen Suggs', 'Franz Wagner', 'Moritz Wagner'],
        conference: 'Eastern'
    },

    {
        teamId: 22,
        name: 'Philadelphia 76ers',
        gamesPlayed: 49,
        wins: 30,
        losses: 19,
        minutesPlayed: 48.2,
        points: 118.8,
        fieldGoalsMade: 42.4,
        fieldGoalsAttempted: 89.1,
        threePointFieldGoalsMade: 11.4,
        threePointFieldGoalsAttempted: 31.4,
        freeThrowsMade: 22.6,
        freeThrowsAttempted: 27.2,
        offensiveRebounds: 11.0,
        defensiveRebounds: 32.1,
        rebounds: 43.1,
        assists: 24.8,
        turnovers: 11.9,
        steals: 8.9,
        blocks: 5.9,
        personalFouls: 20.9,
        plusMinus: 5.4,

        record: '30 - 19',
        placement: '5th in Eastern',
        pointsPerGame: 118.5,
        reboundsPerGame: 43.3,
        assistsPerGame: 24.8,

        roster: ['Mo Bamba', 'Nicolas Batum', 'Robert Covington', 'Joel Embiid', 'Tobias Harris',
                 'Buddy Hield', 'Kenyon Martin Jr.', 'Tyrese Maxey', 'De\'Anthony Melton', 'Kelly Oubre Jr.',
                 'Cameron Payne', 'Paul Reed'],
        conference: 'Eastern'
    },

    {
        teamId: 23,
        name: 'Phoenix Suns',
        gamesPlayed: 50,
        wins: 29,
        losses: 21,
        minutesPlayed: 48.3,
        points: 117.3,
        fieldGoalsMade: 42.6,
        fieldGoalsAttempted: 85.5,
        threePointFieldGoalsMade: 12.0,
        threePointFieldGoalsAttempted: 31.5,
        freeThrowsMade: 20.2,
        freeThrowsAttempted: 24.9,
        offensiveRebounds: 10.0,
        defensiveRebounds: 33.2,
        rebounds: 43.1,
        assists: 26.7,
        turnovers: 14.9,
        steals: 7.3,
        blocks: 5.9,
        personalFouls: 18.5,
        plusMinus: 2.7,

        record: '29 - 21',
        placement: '7th in Western',
        pointsPerGame: 117.4,
        reboundsPerGame: 43.1,
        assistsPerGame: 26.7,

        roster: ['Grayson Allen', 'Bradley Beal', 'Bol Bol', 'Devin Booker', 'Kevin Durant', 'Drew Eubanks', 'Eric Gordon', 'Damion Lee',
                 'Nassir Little', 'Jusuf Nurkic', 'Josh Okogie', 'Royce O\'Neale', 'David Roddy'],
        conference: 'Western'
    },

    {
        teamId: 24,
        name: 'Portland Trail Blazers',
        gamesPlayed: 50,
        wins: 15,
        losses: 35,
        minutesPlayed: 48.5,
        points: 108.4,
        fieldGoalsMade: 39.5,
        fieldGoalsAttempted: 89.7,
        threePointFieldGoalsMade: 12.0,
        threePointFieldGoalsAttempted: 33.9,
        freeThrowsMade: 17.4,
        freeThrowsAttempted: 21.8,
        offensiveRebounds: 11.9,
        defensiveRebounds: 29.6,
        rebounds: 41.5,
        assists: 22.6,
        turnovers: 14.8,
        steals: 7.8,
        blocks: 4.6,
        personalFouls: 20.3,
        plusMinus: -8.3,

        record: '15 - 35',
        placement: '14th in Western',
        pointsPerGame: 108.2,
        reboundsPerGame: 41.4,
        assistsPerGame: 22.7,

        roster: ['Deandre Ayton', 'Dalano Banton', 'Malcom Brogdon', 'Moses Brown', 'Toumani Camara', 'Jerami Grant', 'Ashton Hagans',
                 'Scoot Henderson', 'Kris Murray', 'Rayan Rupert', 'Shaedon Sharpe', 'Anfernee Simons', 'Matisse Thybulle', 'Jabari Walker', 'Robert Williams III'],
        conference: 'Western'
    },

    {
        teamId: 25,
        name: 'Sacramento Kings',
        gamesPlayed: 49,
        wins: 29,
        losses: 20,
        minutesPlayed: 48.5,
        points: 118.3,
        fieldGoalsMade: 43.7,
        fieldGoalsAttempted: 90.9,
        threePointFieldGoalsMade: 14.9,
        threePointFieldGoalsAttempted: 40.3,
        freeThrowsMade: 16.1,
        freeThrowsAttempted: 22.0,
        offensiveRebounds: 10.4,
        defensiveRebounds: 33.0,
        rebounds: 43.3,
        assists: 28.7,
        turnovers: 13.5,
        steals: 7.2,
        blocks: 3.9,
        personalFouls: 20.0,
        plusMinus: 0.5,

        record: '29 - 20',
        placement: '5th in Western',
        pointsPerGame: 118.7,
        reboundsPerGame: 43.1,
        assistsPerGame: 28.8,

        roster: ['Harrison Barnes', 'Chris Duarte', 'Kessler Edwards', 'Keon Ellis', 'De\'Aaron Fox', 'Kevin Huerter', 'Colby Jones', 'Alex Len',
                 'Trey Lyles', 'JaVale McGee', 'Davion Mitchell', 'Malik Monk', 'Keegan Murray', 'Domantas Sabonis', 'Sasha Vezenkov'],
        conference: 'Western'
    },

    {
        teamId: 26,
        name: 'San Antonio Spurs',
        gamesPlayed: 50,
        wins: 10,
        losses: 40,
        minutesPlayed: 48.2,
        points: 112.3,
        fieldGoalsMade: 42.0,
        fieldGoalsAttempted: 91.3,
        threePointFieldGoalsMade: 12.5,
        threePointFieldGoalsAttempted: 36.6,
        freeThrowsMade: 15.8,
        freeThrowsAttempted: 20.3,
        offensiveRebounds: 10.4,
        defensiveRebounds: 33.1,
        rebounds: 43.4,
        assists: 29.3,
        turnovers: 14.8,
        steals: 7.2,
        blocks: 6.1,
        personalFouls: 18.3,
        plusMinus: -8.5,

        record: '10 - 40',
        placement: '15th in Western',
        pointsPerGame: 112.0,
        reboundsPerGame: 43.1,
        assistsPerGame: 29.2,

        roster: ['Charles Bassey', 'Malaki Branham', 'Julian Champagnie', 'Sidy Cissoko', 'Zach Collins', 'Devote\' Graham', 'Keldon Johnson', 'Tre Jones',
                 'Sandro Mamukelashvili', 'Marcus Morris Sr.', 'Cedi Osman', 'Jeremy Sochan', 'Devin Vassell', 'Victor Wembanyama', 'Blake Wesley'],
        conference: 'Western'
    },

    {
        teamId: 27,
        name: 'Toronto Raptors',
        gamesPlayed: 50,
        wins: 17,
        losses: 33,
        minutesPlayed: 48.4,
        points: 114.3,
        fieldGoalsMade: 42.9,
        fieldGoalsAttempted: 89.7,
        threePointFieldGoalsMade: 11.8,
        threePointFieldGoalsAttempted: 32.9,
        freeThrowsMade: 16.6,
        freeThrowsAttempted: 22.4,
        offensiveRebounds: 11.2,
        defensiveRebounds: 32.2,
        rebounds: 43.4,
        assists: 29.5,
        turnovers: 13.5,
        steals: 7.5,
        blocks: 4.9,
        personalFouls: 18.5,
        plusMinus: -3.5,

        record: '17 - 33',
        placement: '12th in Eastern',
        pointsPerGame: 113.9,
        reboundsPerGame: 43.3,
        assistsPerGame: 29.2,

        roster: ['Ochai Agbaji', 'Scottie Barnes', 'RJ Barrett', 'Chris Boucher', 'Bruce Brown', 
                 'Gradey Dick', 'Mouhamadou Gueye', 'Jordan Nwora', 'Kelly Olynyk', 'Jakob Poeltl',
                 'Immanuel Quickley', 'Garrett Temple', 'Gary Trent Jr.', 'Justise Winslow'],
        conference: 'Eastern'
    },

    {
        teamId: 28,
        name: 'Utah Jazz',
        gamesPlayed: 51,
        wins: 25,
        losses: 26,
        minutesPlayed: 48.5,
        points: 117.7,
        fieldGoalsMade: 42.7,
        fieldGoalsAttempted: 90.6,
        threePointFieldGoalsMade: 13.2,
        threePointFieldGoalsAttempted: 36.9,
        freeThrowsMade: 19.1,
        freeThrowsAttempted: 23.3,
        offensiveRebounds: 12.7,
        defensiveRebounds: 33.9,
        rebounds: 46.6,
        assists: 28.4,
        turnovers: 15.8,
        steals: 6.6,
        blocks: 5.9,
        personalFouls: 20.3,
        plusMinus: -2.0,

        record: '25 - 26',
        placement: '10th in Western',
        pointsPerGame: 117.8,
        reboundsPerGame: 46.7,
        assistsPerGame: 28.4,

        roster: ['Jordan Clarkson', 'John Collins', 'Kris Dunn', 'Keyonte George', 'Taylor Hendricks', 'Talen Horton-Tucker',
                 'Walker Kessler', 'Kira Lewis Jr.', 'Lauri Markkanen', 'Otto Porter Jr.', 'Luka Samanic', 'Brice Sensabaugh', 'Collin Sexton', 'Omer Yurtseven'],
        conference: 'Western'
    },

    {
        teamId: 29,
        name: 'Washington Wizards',
        gamesPlayed: 49,
        wins: 9,
        losses: 40,
        minutesPlayed: 48.0,
        points: 114.7,
        fieldGoalsMade: 43.3,
        fieldGoalsAttempted: 91.0,
        threePointFieldGoalsMade: 11.8,
        threePointFieldGoalsAttempted: 34.1,
        freeThrowsMade: 16.3,
        freeThrowsAttempted: 21.2,
        offensiveRebounds: 9.1,
        defensiveRebounds: 31.3,
        rebounds: 40.4,
        assists: 28.0,
        turnovers: 13.7,
        steals: 7.7,
        blocks: 5.5,
        personalFouls: 19.8,
        plusMinus: -9.3,

        record: '9 - 40',
        placement: '14th in Eastern',
        pointsPerGame: 114.8,
        reboundsPerGame: 40.5,
        assistsPerGame: 28.0,

        roster: ['Deni Avdija', 'Marvin Bagley III', 'Patrick Baldwin Jr.', 'Bilal Coulibaly', 'Johnny Davis', 'Anthony Gill', 'Richaun Holmes',
                 'Tyus Jones', 'Corey Kispert', 'Kyle Kuzma', 'Isaiah Livers', 'Jordan Poole', 'Landry Shamet', 'Delon Wright'],
        conference: 'Eastern'
    },

    {
        teamId: 30,
        name: 'Atlanta Hawks',
        gamesPlayed: 50,
        wins: 22,
        losses: 28,
        minutesPlayed: 48.4,
        points: 121.6,
        fieldGoalsMade: 43.8,
        fieldGoalsAttempted: 93.8,
        threePointFieldGoalsMade: 13.8,
        threePointFieldGoalsAttempted: 38.0,
        freeThrowsMade: 20.2,
        freeThrowsAttempted: 24.9,
        offensiveRebounds: 13.1,
        defensiveRebounds: 31.8,
        rebounds: 44.9,
        assists: 26.1,
        turnovers: 13.5,
        steals: 7.8,
        blocks: 4.4,
        personalFouls: 18.9,
        plusMinus: -2.3,

        record: '22 - 28',
        placement: '10th in Eastern',
        pointsPerGame: 121.7,
        reboundsPerGame: 44.8,
        assistsPerGame: 26.2,

        roster: ['Saddiq Bey', 'Bogdan Bogdanovic', 'Kobe Bufkin', 'Clint Capela', 'Bruno Fernando', 
                 'Trent Forrest', 'AJ Griffin', 'Mouhamed Gueye', 'De\'Andre Hunter', 'Jalen Johnson',
                 'Garrison Mathews', 'Wesley Matthews', 'Patty Mills', 'Dejounte Murray', 'Onyeka Okongwu', 'Trae Young'],
        conference: 'Eastern'
    }
]