export const PLAYERS: any = [
    {
        id: 0,
        teamId: 16,
        playerId: 203507,
        fullName: 'Giannis Antetokounmpo',
        team: 'Milwaukee Bucks',
        age: 29,
        gamesPlayed: 46,
        wins: 31,
        losses: 15,
        minutes: 1618.1,
        points: 1421,
        fieldGoalsMade: 530,
        fieldGoalsAttempted: 872,
        threePointFieldGoalsMade: 20,
        threePointFieldGoalsAttempted: 79,
        freeThrowsMade: 341,
        freeThrowsAttempted: 516,
        offensiveRebounds: 121,
        defensiveRebounds: 412,
        rebounds: 533,
        assists: 282,
        turnovers: 166,
        steals: 63,
        blocks: 51,
        personalFouls: 139,
        plusMinus: 269,
        
        position: 'Forward',
        jerseyNumber: 34,
        pointsPerGame: 30.9,
        reboundsPerGame: 11.6,
        assistsPerGame: 6.1,
        pie: 19.3,
        height: 211,
        weight: 109, 
        birthdate: 'December 6, 1994',
        country: 'Greece',
        lastAttended: 'Filathlitikos',
        draft: '2013 R1 Pick 15'
    },

    {
        id: 1,
        teamId: 6,
        playerId: 1629029,
        fullName: 'Luka Doncic',
        team: 'Dallas Mavericks',
        age: 24,
        gamesPlayed: 40,
        wins: 23,
        losses: 17,
        minutes: 1499.4,
        points: 1388,
        fieldGoalsMade: 469,
        fieldGoalsAttempted: 960,
        threePointFieldGoalsMade: 155,
        threePointFieldGoalsAttempted: 413,
        freeThrowsMade: 295,
        freeThrowsAttempted: 378,
        offensiveRebounds: 32,
        defensiveRebounds: 312,
        rebounds: 344,
        assists: 382,
        turnovers: 157,
        steals: 57,
        blocks: 24,
        personalFouls: 74,
        plusMinus: 39,
        
        position: 'Forward-Guard',
        jerseyNumber: 77,
        pointsPerGame: 34.7,
        reboundsPerGame: 8.6,
        assistsPerGame: 9.6,
        pie: 20.1,
        height: 201,
        weight: 104, 
        birthdate: 'February 28, 1999',
        country: 'Slovenia',
        lastAttended: 'Real Madrid',
        draft: '2018 R1 Pick 3'
    },

    {
        id: 2,
        teamId: 13,
        playerId: 2544,
        fullName: 'LeBron James',
        team: 'Los Angeles Lakers',
        age: 39,
        gamesPlayed: 46,
        wins: 31,
        losses: 15,
        minutes: 1618.1,
        points: 1421,
        fieldGoalsMade: 530,
        fieldGoalsAttempted: 872,
        threePointFieldGoalsMade: 20,
        threePointFieldGoalsAttempted: 79,
        freeThrowsMade: 341,
        freeThrowsAttempted: 516,
        offensiveRebounds: 121,
        defensiveRebounds: 412,
        rebounds: 533,
        assists: 282,
        turnovers: 166,
        steals: 63,
        blocks: 51,
        personalFouls: 139,
        plusMinus: 269,
        
        position: 'Forward',
        jerseyNumber: 34,
        pointsPerGame: 30.9,
        reboundsPerGame: 11.6,
        assistsPerGame: 6.1,
        pie: 19.3,
        height: 211,
        weight: 109, 
        birthdate: 'December 6, 1994',
        country: 'Greece',
        lastAttended: 'Filathlitikos',
        draft: '2013 R1 Pick 15'
    },

    {
        id: 3,
        teamId: 7,
        playerId: 203999,
        fullName: 'Nikola Jokic',
        team: 'Denver Nuggets',
        age: 28,
        gamesPlayed: 48,
        wins: 33,
        losses: 15,
        minutes: 1622.3,
        points: 1262,
        fieldGoalsMade: 492,
        fieldGoalsAttempted: 838,
        threePointFieldGoalsMade: 50,
        threePointFieldGoalsAttempted: 138,
        freeThrowsMade: 228,
        freeThrowsAttempted: 279,
        offensiveRebounds: 148,
        defensiveRebounds: 443,
        rebounds: 591,
        assists: 435,
        turnovers: 142,
        steals: 56,
        blocks: 45,
        personalFouls: 124,
        plusMinus: 368,
        
        position: 'Center',
        jerseyNumber: 15,
        pointsPerGame: 26.3,
        reboundsPerGame: 12.3,
        assistsPerGame: 9.1,
        pie: 21.7,
        height: 211,
        weight: 129, 
        birthdate: 'February 19, 1995',
        country: 'Serbia',
        lastAttended: 'Mega Basket',
        draft: '2014 R2 Pick 41'
    },

    {
        id: 4,
        teamId: 11,
        playerId: 1630169,
        fullName: 'Tyrese Haliburton',
        team: 'Indiana Pacers',
        age: 23,
        gamesPlayed: 37,
        wins: 20,
        losses: 17,
        minutes: 1201.5,
        points: 843,
        fieldGoalsMade: 301,
        fieldGoalsAttempted: 609,
        threePointFieldGoalsMade: 118,
        threePointFieldGoalsAttempted: 299,
        freeThrowsMade: 123,
        freeThrowsAttempted: 142,
        offensiveRebounds: 25,
        defensiveRebounds: 126,
        rebounds: 151,
        assists: 444,
        turnovers: 91,
        steals: 39,
        blocks: 24,
        personalFouls: 39,
        plusMinus: 156,
        
        position: 'Guard',
        jerseyNumber: 0,
        pointsPerGame: 22.8,
        reboundsPerGame: 4.1,
        assistsPerGame: 12.0,
        pie: 17.2,
        height: 196,
        weight: 84, 
        birthdate: 'February 29, 2000',
        country: 'USA',
        lastAttended: 'Iowa State',
        draft: '2020 R1 Pick 12'
    },

    {
        id: 5,
        teamId: 20,
        playerId: 1628983,
        fullName: 'Shai Gilgeous-Alexander',
        team: 'Oklahoma City Thunder',
        age: '25',
        gamesPlayed: 48,
        wins: 34,
        losses: 14,
        minutes: 1645.0,
        points: 1503,
        fieldGoalsMade: 525,
        fieldGoalsAttempted: 958,
        threePointFieldGoalsMade: 57,
        threePointFieldGoalsAttempted: 162,
        freeThrowsMade: 396,
        freeThrowsAttempted: 445,
        offensiveRebounds: 44,
        defensiveRebounds: 224,
        rebounds: 268,
        assists: 308,
        turnovers: 105,
        steals: 109,
        blocks: 39,
        personalFouls: 122,
        plusMinus: 413,
        
        position: 'Guard',
        jerseyNumber: 2,
        pointsPerGame: 31.3,
        reboundsPerGame: 5.6,
        assistsPerGame: 6.4,
        pie: 19.9,
        height: 198,
        weight: 88, 
        birthdate: 'July 12, 1998',
        country: 'Canada',
        lastAttended: 'Kentucky',
        draft: '2018 R1 Pick 11'
    },

    {
        id: 6,
        teamId: 16,
        playerId: 203081,
        fullName: 'Damian Lillard',
        team: 'Milwaukee Bucks',
        age: '33',
        gamesPlayed: 45,
        wins: 32,
        losses: 13,
        minutes: 1587.3,
        points: 1130,
        fieldGoalsMade: 333,
        fieldGoalsAttempted: 790,
        threePointFieldGoalsMade: 133,
        threePointFieldGoalsAttempted: 388,
        freeThrowsMade: 331,
        freeThrowsAttempted: 358,
        offensiveRebounds: 26,
        defensiveRebounds: 168,
        rebounds: 194,
        assists: 304,
        turnovers: 111,
        steals: 48,
        blocks: 7,
        personalFouls: 71,
        plusMinus: 229,
        
        position: 'Guard',
        jerseyNumber: 0,
        pointsPerGame: 25.1,
        reboundsPerGame: 4.3,
        assistsPerGame: 6.8,
        pie: 13.5,
        height: 188,
        weight: 88, 
        birthdate: 'July 15, 1990',
        country: 'USA',
        lastAttended: 'Weber State',
        draft: '2012 R1 Pick 6'
    },

    {
        id: 7,
        teamId: 23,
        playerId: 201142,
        fullName: 'Kevin Durant',
        team: 'Phoenix Suns',
        age: '35',
        gamesPlayed: 42,
        wins: 23,
        losses: 19,
        minutes: 1566.7,
        points: 1199,
        fieldGoalsMade: 430,
        fieldGoalsAttempted: 804,
        threePointFieldGoalsMade: 97,
        threePointFieldGoalsAttempted: 214,
        freeThrowsMade: 242,
        freeThrowsAttempted: 276,
        offensiveRebounds: 22,
        defensiveRebounds: 247,
        rebounds: 269,
        assists: 244,
        turnovers: 132,
        steals: 36,
        blocks: 53,
        personalFouls: 79,
        plusMinus: 135,
        
        position: 'Forward',
        jerseyNumber: 35,
        pointsPerGame: 28.5,
        reboundsPerGame: 6.4,
        assistsPerGame: 5.8,
        pie: 16.1,
        height: 211,
        weight: 109, 
        birthdate: 'September 29, 1988',
        country: 'USA',
        lastAttended: 'Texas',
        draft: '2007 R1 Pick 2'
    },
    
    {
        id: 8,
        teamId: 9,
        playerId: 201939,
        fullName: 'Stephen Curry',
        team: 'Golden State Warriors',
        age: '35',
        gamesPlayed: 42,
        wins: 21,
        losses: 21,
        minutes: 1407.1,
        points: 1149,
        fieldGoalsMade: 368,
        fieldGoalsAttempted: 812,
        threePointFieldGoalsMade: 199,
        threePointFieldGoalsAttempted: 486,
        freeThrowsMade: 214,
        freeThrowsAttempted: 230,
        offensiveRebounds: 19,
        defensiveRebounds: 163,
        rebounds: 182,
        assists: 211,
        turnovers: 128,
        steals: 35,
        blocks: 16,
        personalFouls: 78,
        plusMinus: -14,
        
        position: 'Guard',
        jerseyNumber: 30,
        pointsPerGame: 27.4,
        reboundsPerGame: 4.3,
        assistsPerGame: 5.0,
        pie: 14.1,
        height: 188,
        weight: 84, 
        birthdate: 'March 14, 1988',
        country: 'USA',
        lastAttended: 'Davidson',
        draft: '2009 R1 Pick 7'
    },

    {
        id: 9,
        teamId: 16,
        playerId: 203114,
        fullName: 'Khris Middleton',
        team: 'Milwaukee Bucks',
        age: '32',
        gamesPlayed: 43,
        wins: 21,
        losses: 21,
        minutes: 1129,
        points: 636,
        fieldGoalsMade: 242,
        fieldGoalsAttempted: 497,
        threePointFieldGoalsMade: 73,
        threePointFieldGoalsAttempted: 193,
        freeThrowsMade: 79,
        freeThrowsAttempted: 95,
        offensiveRebounds: 26,
        defensiveRebounds: 158,
        rebounds: 184,
        assists: 216,
        turnovers: 89,
        steals: 38,
        blocks: 13,
        personalFouls: 104,
        plusMinus: 5,
        
        position: 'Forward',
        jerseyNumber: 22,
        pointsPerGame: 14.8,
        reboundsPerGame: 4.3,
        assistsPerGame: 5.0,
        pie: 11.6,
        height: 201,
        weight: 101, 
        birthdate: 'August 12, 1991',
        country: 'USA',
        lastAttended: 'Texas A&M',
        draft: '2012 R2 Pick 39'
    }
]